use super::mark_mutation;
use super::Element;
use crate::ace::engine::dom::AceNodeType;
use rquickjs::{prelude::Rest, Class, Ctx, Result, Value};
use std::sync::{Arc, Mutex};


pub mod append_child; pub use append_child::*;
pub mod append_child_generic; pub use append_child_generic::*;
pub mod remove_child; pub use remove_child::*;
pub mod parent_node; pub use parent_node::*;
pub mod first_child; pub use first_child::*;
pub mod last_child; pub use last_child::*;
pub mod next_sibling; pub use next_sibling::*;
pub mod previous_sibling; pub use previous_sibling::*;
pub mod append; pub use append::*;
pub mod prepend; pub use prepend::*;
pub mod children; pub use children::*;
pub mod parent_element; pub use parent_element::*;
pub mod first_element_child; pub use first_element_child::*;
pub mod last_element_child; pub use last_element_child::*;
pub mod next_element_sibling; pub use next_element_sibling::*;
pub mod previous_element_sibling; pub use previous_element_sibling::*;
pub mod child_element_count; pub use child_element_count::*;
pub mod insert_before; pub use insert_before::*;
pub mod remove; pub use remove::*;
pub mod contains; pub use contains::*;
pub mod is_same_node; pub use is_same_node::*;
pub mod get_text_content; pub use get_text_content::*;
pub mod set_text_content; pub use set_text_content::*;
pub mod insert_adjacent_html; pub use insert_adjacent_html::*;
pub mod insert_adjacent_element; pub use insert_adjacent_element::*;
