use std::collections::BTreeMap;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

fn main() {
    println!("cargo:rerun-if-changed=src/ui/appwindow.slint");
    println!("cargo:rerun-if-changed=src/ace/html/entities.json");
    println!("cargo:rerun-if-changed=scripts/lint.sh");
    println!("cargo:rerun-if-changed=scripts/lint.ps1");

    run_lint_checks();

    slint_build::compile("src/ui/appwindow.slint").unwrap();
    generate_html_entities().unwrap();
}

fn run_lint_checks() {
    // Skip lint checks if SKIP_LINT environment variable is set
    if std::env::var("SKIP_LINT").is_ok() {
        eprintln!("warning: skipping lint checks (SKIP_LINT set)");
        return;
    }

    let status = if cfg!(target_os = "windows") {
        Command::new("powershell")
            .args(["-ExecutionPolicy", "Bypass", "-File", "scripts/lint.ps1"])
            .status()
    } else {
        Command::new("bash")
            .args(["scripts/lint.sh"])
            .status()
    };

    match status {
        Ok(s) if !s.success() => {
            panic!(
                "\n\nLint checks failed!\n\
                 Run './scripts/lint.sh --all' for details.\n\
                 Fix the errors above before building.\n\n"
            );
        }
        Err(e) => {
            eprintln!("warning: could not run lint script: {}", e);
            eprintln!("warning: skipping lint checks");
        }
        _ => {}
    }
}

fn generate_html_entities() -> Result<(), Box<dyn std::error::Error>> {
    let source_path = PathBuf::from("src/ace/html/entities.json");
    let raw = fs::read_to_string(source_path)?;
    let value: serde_json::Value = serde_json::from_str(&raw)?;
    let obj = value
        .as_object()
        .ok_or("entities.json root must be an object")?;

    let mut map = BTreeMap::<String, String>::new();

    for (key, entry) in obj {
        let name = key.to_string();
        if name.is_empty() {
            continue;
        }

        let characters = entry
            .get("characters")
            .and_then(serde_json::Value::as_str)
            .ok_or("entity entry missing 'characters'")?;

        map.insert(name, characters.to_string());
    }

    let mut generated = String::new();
    generated.push_str("// @generated by build.rs - do not edit manually.\n");
    generated.push_str(&format!(
        "pub static HTML_ENTITIES: [(&str, &str); {}] = [\n",
        map.len()
    ));

    for (name, chars) in &map {
        generated.push_str(&format!("    ({:?}, {:?}),\n", name, chars));
    }

    generated.push_str("];\n\n");
    generated.push_str("pub fn lookup_named_entity(name: &str) -> Option<&'static str> {\n");
    generated.push_str(
        "    HTML_ENTITIES.binary_search_by_key(&name, |(entity, _)| *entity).ok().map(|idx| HTML_ENTITIES[idx].1)\n",
    );
    generated.push_str("}\n");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR")?);
    let out_file = out_dir.join("html_entities.rs");
    fs::write(out_file, generated)?;
    Ok(())
}
