use super::{mark_mutation, Element};
use crate::ace::engine::dom::{AceDOM, AceNode, AceNodeType};
use rquickjs::{Class, Ctx, Result, Value};


pub mod tag_name; pub use tag_name::*;
pub mod id; pub use id::*;
pub mod set_id; pub use set_id::*;
pub mod class_name; pub use class_name::*;
pub mod set_class_name; pub use set_class_name::*;
pub mod name; pub use name::*;
pub mod set_name; pub use set_name::*;
pub mod title_prop; pub use title_prop::*;
pub mod set_title_prop; pub use set_title_prop::*;
pub mod src; pub use src::*;
pub mod set_src; pub use set_src::*;
pub mod href; pub use href::*;
pub mod set_href; pub use set_href::*;
pub mod value; pub use value::*;
pub mod set_value; pub use set_value::*;
pub mod checked; pub use checked::*;
pub mod set_checked; pub use set_checked::*;
pub mod width; pub use width::*;
pub mod set_width; pub use set_width::*;
pub mod height; pub use height::*;
pub mod set_height; pub use set_height::*;
pub mod natural_width; pub use natural_width::*;
pub mod natural_height; pub use natural_height::*;
pub mod complete; pub use complete::*;
pub mod text_content; pub use text_content::*;
pub mod collect_text; pub use collect_text::*;
pub mod inner_text; pub use inner_text::*;
pub mod set_text_content; pub use set_text_content::*;
pub mod get_attribute; pub use get_attribute::*;
pub mod get_attribute_names; pub use get_attribute_names::*;
pub mod set_attribute; pub use set_attribute::*;
pub mod has_attribute; pub use has_attribute::*;
pub mod remove_attribute; pub use remove_attribute::*;
pub mod inner_html; pub use inner_html::*;
pub mod set_inner_html; pub use set_inner_html::*;
pub mod outer_html; pub use outer_html::*;
pub mod set_outer_html; pub use set_outer_html::*;
pub mod offset_parent; pub use offset_parent::*;
pub mod offset_top; pub use offset_top::*;
pub mod offset_left; pub use offset_left::*;
pub mod offset_width; pub use offset_width::*;
pub mod offset_height; pub use offset_height::*;
pub mod client_top; pub use client_top::*;
pub mod client_left; pub use client_left::*;
pub mod client_width; pub use client_width::*;
pub mod client_height; pub use client_height::*;
pub mod scroll_top; pub use scroll_top::*;
pub mod set_scroll_top; pub use set_scroll_top::*;
pub mod scroll_left; pub use scroll_left::*;
pub mod set_scroll_left; pub use set_scroll_left::*;
pub mod scroll_width; pub use scroll_width::*;
pub mod scroll_height; pub use scroll_height::*;
pub mod attach_shadow; pub use attach_shadow::*;
