[net]
git-fetch-with-cli = true
retry = 3

[http]
check-revoke = false
multiplexing = false

[target.x86_64-pc-windows-gnu]
linker = "C:\\Users\\24802449\\AppData\\Local\\Microsoft\\WinGet\\Packages\\BrechtSanders.WinLibs.POSIX.UCRT_Microsoft.Winget.Source_8wekyb3d8bbwe\\mingw64\\bin\\x86_64-w64-mingw32-gcc.exe"
