use std::fmt::Write;
use crate::ace::html::{parse_fragment, HtmlDocument, HtmlNode, is_void_element};

pub mod nodeid; pub use nodeid::*;
pub mod nodetype; pub use nodetype::*;
pub mod noderef; pub use noderef::*;
pub mod acedom; pub use acedom::*;
pub mod domobserver; pub use domobserver::*;
pub mod mutationobserverinit; pub use mutationobserverinit::*;
pub mod mutationtype; pub use mutationtype::*;
pub mod mutationrecord; pub use mutationrecord::*;
pub mod nodedirtyflags; pub use nodedirtyflags::*;
pub mod acenode; pub use acenode::*;
pub mod acenodetype; pub use acenodetype::*;
pub mod aceelement; pub use aceelement::*;
pub mod acedom_impl_1; pub use acedom_impl_1::*;
pub mod acedom_impl_2; pub use acedom_impl_2::*;
pub mod acedom_impl_3; pub use acedom_impl_3::*;
pub mod acedom_impl_4; pub use acedom_impl_4::*;
pub mod acedom_impl_5; pub use acedom_impl_5::*;
pub mod acedom_impl_6; pub use acedom_impl_6::*;
pub mod acedom_impl_7; pub use acedom_impl_7::*;
pub mod acedom_impl_8; pub use acedom_impl_8::*;
pub mod acedom_impl_9; pub use acedom_impl_9::*;
pub mod make_element_dom; pub use make_element_dom::*;

pub mod arena;
pub mod live_nodelist;
pub mod range;
pub mod selection;
pub mod shadow;
pub mod custom_elements;
pub mod a11y;
pub mod virtual_dom;
pub mod string_intern;
pub mod wpt_harness;
pub mod benchmarks;
