//! # Tabela de Entidades HTML5 Nomeadas (WHATWG Named Character References)
//!
//! Tabela estática de dispersão perfeita ($O(1)$) com as principais e mais frequentes entidades da Web.

use phf::phf_map;

/// Mapa estático perfeito para resolução instantânea de entidades nomeadas HTML5.
pub static NAMED_ENTITIES: phf::Map<&'static str, &'static str> = phf_map! {
    // 1. Entidades Fundamentais XML / HTML
    "amp" => "&",
    "amp;" => "&",
    "lt" => "<",
    "lt;" => "<",
    "gt" => ">",
    "gt;" => ">",
    "quot" => "\"",
    "quot;" => "\"",
    "apos;" => "'",
    "nbsp" => "\u{00A0}",
    "nbsp;" => "\u{00A0}",

    // 2. Pontuação e Tipografia
    "copy" => "©",
    "copy;" => "©",
    "reg" => "®",
    "reg;" => "®",
    "trade" => "™",
    "trade;" => "™",
    "ndash" => "–",
    "ndash;" => "–",
    "mdash" => "—",
    "mdash;" => "—",
    "lsquo;" => "‘",
    "rsquo;" => "’",
    "sbquo;" => "‚",
    "ldquo;" => "“",
    "rdquo;" => "”",
    "bdquo;" => "„",
    "dagger;" => "†",
    "Dagger;" => "‡",
    "bull;" => "•",
    "hellip;" => "…",
    "permil;" => "‰",
    "prime;" => "′",
    "Prime;" => "″",
    "lsaquo;" => "‹",
    "rsaquo;" => "›",
    "oline;" => "‾",
    "frasl;" => "⁄",
    "euro" => "€",
    "euro;" => "€",
    "pound" => "£",
    "pound;" => "£",
    "yen" => "¥",
    "yen;" => "¥",
    "cent" => "¢",
    "cent;" => "¢",
    "curren" => "¤",
    "curren;" => "¤",
    "sect" => "§",
    "sect;" => "§",
    "deg" => "°",
    "deg;" => "°",
    "plusmn" => "±",
    "plusmn;" => "±",
    "sup2" => "²",
    "sup2;" => "²",
    "sup3" => "³",
    "sup3;" => "³",
    "micro" => "µ",
    "micro;" => "µ",
    "para" => "¶",
    "para;" => "¶",
    "middot" => "·",
    "middot;" => "·",
    "frac14" => "¼",
    "frac14;" => "¼",
    "frac12" => "½",
    "frac12;" => "½",
    "frac34" => "¾",
    "frac34;" => "¾",
    "iquest" => "¿",
    "iquest;" => "¿",
    "iexcl" => "¡",
    "iexcl;" => "¡",
    "laquo" => "«",
    "laquo;" => "«",
    "raquo" => "»",
    "raquo;" => "»",

    // 3. Controle de Direção e Espaçamento Unicode
    "zwnj;" => "\u{200C}",
    "zwj;" => "\u{200D}",
    "lrm;" => "\u{200E}",
    "rlm;" => "\u{200F}",

    // 4. Caracteres Acentuados Latin (Minúsculas)
    "aacute" => "á", "aacute;" => "á",
    "eacute" => "é", "eacute;" => "é",
    "iacute" => "í", "iacute;" => "í",
    "oacute" => "ó", "oacute;" => "ó",
    "uacute" => "ú", "uacute;" => "ú",
    "ccedil" => "ç", "ccedil;" => "ç",
    "atilde" => "ã", "atilde;" => "ã",
    "otilde" => "õ", "otilde;" => "õ",
    "ntilde" => "ñ", "ntilde;" => "ñ",
    "agrave" => "à", "agrave;" => "à",
    "egrave" => "è", "egrave;" => "è",
    "igrave" => "ì", "igrave;" => "ì",
    "ograve" => "ò", "ograve;" => "ò",
    "ugrave" => "ù", "ugrave;" => "ù",
    "auml" => "ä", "auml;" => "ä",
    "euml" => "ë", "euml;" => "ë",
    "iuml" => "ï", "iuml;" => "ï",
    "ouml" => "ö", "ouml;" => "ö",
    "uuml" => "ü", "uuml;" => "ü",
    "yuml" => "ÿ", "yuml;" => "ÿ",
    "acirc" => "â", "acirc;" => "â",
    "ecirc" => "ê", "ecirc;" => "ê",
    "icirc" => "î", "icirc;" => "î",
    "ocirc" => "ô", "ocirc;" => "ô",
    "ucirc" => "û", "ucirc;" => "û",
    "aring" => "å", "aring;" => "å",
    "aelig" => "æ", "aelig;" => "æ",
    "szlig" => "ß", "szlig;" => "ß",
    "eth" => "ð", "eth;" => "ð",
    "thorn" => "þ", "thorn;" => "þ",

    // 5. Caracteres Acentuados Latin (Maiúsculas)
    "Aacute" => "Á", "Aacute;" => "Á",
    "Eacute" => "É", "Eacute;" => "É",
    "Iacute" => "Í", "Iacute;" => "Í",
    "Oacute" => "Ó", "Oacute;" => "Ó",
    "Uacute" => "Ú", "Uacute;" => "Ú",
    "Ccedil" => "Ç", "Ccedil;" => "Ç",
    "Atilde" => "Ã", "Atilde;" => "Ã",
    "Otilde" => "Õ", "Otilde;" => "Õ",
    "Ntilde" => "Ñ", "Ntilde;" => "Ñ",
    "Agrave" => "À", "Agrave;" => "À",
    "Egrave" => "È", "Egrave;" => "È",
    "Igrave" => "Ì", "Igrave;" => "Ì",
    "Ograve" => "Ò", "Ograve;" => "Ò",
    "Ugrave" => "Ù", "Ugrave;" => "Ù",
    "Auml" => "Ä", "Auml;" => "Ä",
    "Euml" => "Ë", "Euml;" => "Ë",
    "Iuml" => "Ï", "Iuml;" => "Ï",
    "Ouml" => "Ö", "Ouml;" => "Ö",
    "Uuml" => "Ü", "Uuml;" => "Ü",
    "Acirc" => "Â", "Acirc;" => "Â",
    "Ecirc" => "Ê", "Ecirc;" => "Ê",
    "Icirc" => "Î", "Icirc;" => "Î",
    "Ocirc" => "Ô", "Ocirc;" => "Ô",
    "Ucirc" => "Û", "Ucirc;" => "Û",
    "Aring" => "Å", "Aring;" => "Å",
    "AElig" => "Æ", "AElig;" => "Æ",
    "ETH" => "Ð", "ETH;" => "Ð",
    "THORN" => "Þ", "THORN;" => "Þ",

    // 6. Alfabeto Grego
    "alpha;" => "α", "Alpha;" => "Α",
    "beta;" => "β", "Beta;" => "Β",
    "gamma;" => "γ", "Gamma;" => "Γ",
    "delta;" => "δ", "Delta;" => "Δ",
    "epsilon;" => "ε", "Epsilon;" => "Ε",
    "zeta;" => "ζ", "Zeta;" => "Ζ",
    "eta;" => "η", "Eta;" => "Η",
    "theta;" => "θ", "Theta;" => "Θ",
    "iota;" => "ι", "Iota;" => "Ι",
    "kappa;" => "κ", "Kappa;" => "Κ",
    "lambda;" => "λ", "Lambda;" => "Λ",
    "mu;" => "μ", "Mu;" => "Μ",
    "nu;" => "ν", "Nu;" => "Ν",
    "xi;" => "ξ", "Xi;" => "Ξ",
    "omicron;" => "ο", "Omicron;" => "Ο",
    "pi;" => "π", "Pi;" => "Π",
    "rho;" => "ρ", "Rho;" => "Ρ",
    "sigma;" => "σ", "Sigma;" => "Σ",
    "tau;" => "τ", "Tau;" => "Τ",
    "upsilon;" => "υ", "Upsilon;" => "Υ",
    "phi;" => "φ", "Phi;" => "Φ",
    "chi;" => "χ", "Chi;" => "Χ",
    "psi;" => "ψ", "Psi;" => "Ψ",
    "omega;" => "ω", "Omega;" => "Ω",

    // 7. Símbolos Matemáticos & Lógicos
    "infin;" => "∞",
    "sum;" => "∑",
    "prod;" => "∏",
    "radic;" => "√",
    "prop;" => "∝",
    "ang;" => "∠",
    "and;" => "∧",
    "or;" => "∨",
    "cap;" => "∩",
    "cup;" => "∪",
    "int;" => "∫",
    "there4;" => "∴",
    "sim;" => "∼",
    "cong;" => "≅",
    "asymp;" => "≈",
    "ne;" => "≠",
    "equiv;" => "≡",
    "le;" => "≤",
    "ge;" => "≥",
    "sub;" => "⊂",
    "sup;" => "⊃",
    "nsub;" => "⊄",
    "sube;" => "⊆",
    "supe;" => "⊇",
    "oplus;" => "⊕",
    "otimes;" => "⊗",
    "perp;" => "⊥",
    "sdot;" => "⋅",
    "part;" => "∂",
    "empty;" => "∅",
    "nabla;" => "∇",
    "isin;" => "∈",
    "notin;" => "∉",
    "ni;" => "∋",
    "times;" => "×",
    "divide;" => "÷",

    // 8. Setas e Formas Geométricas
    "larr;" => "←",
    "uarr;" => "↑",
    "rarr;" => "→",
    "darr;" => "↓",
    "harr;" => "↔",
    "crarr;" => "↵",
    "lArr;" => "⇐",
    "uArr;" => "⇑",
    "rArr;" => "⇒",
    "dArr;" => "⇓",
    "hArr;" => "⇔",
    "spades;" => "♠",
    "clubs;" => "♣",
    "hearts;" => "♥",
    "diams;" => "♦",
    "loz;" => "◊",
};
