use crate::ace::engine::dom::{AceDOM, AceNodeType};
use cssparser::{CowRcStr, ParseError, Parser, ParserInput, SourceLocation, ToCss};
use precomputed_hash::PrecomputedHash;
use selectors::attr::{AttrSelectorOperation, CaseSensitivity, NamespaceConstraint};
use selectors::matching::{ElementSelectorFlags, MatchingContext, MatchingMode};
use selectors::OpaqueElement;
use std::collections::HashMap;
pub mod css_values;
use self::css_values::{
    BackgroundImage, BoxShadow, ComputedStyle, CssAlignContent, CssAlignItems, CssBlendMode,
    CssBoxSizing, CssClear, CssColor, CssContent, CssCursor, CssDisplay, CssFlexDirection,
    CssFlexWrap, CssFloat, CssFontWeight, CssJustifyContent, CssLength, CssObjectFit,
    CssObjectPosition, CssOverflow, CssPointerEvents, CssPosition, CssTextAlign, CssTextOverflow,
    CssTextTransform, CssVisibility, CssWhiteSpace, Gradient, GradientStop, TextShadow,
};
use crate::ace::engine::style::css_values::CssFilter;
use crate::ace::engine::style::css_values::TransformFunction;

pub mod animation;


pub mod stylesheet; pub use stylesheet::*;
pub mod acemediarule; pub use acemediarule::*;
pub mod acesupportsrule; pub use acesupportsrule::*;
pub mod acecontainerrule; pub use acecontainerrule::*;
pub mod acerule; pub use acerule::*;
pub mod rulemap; pub use rulemap::*;
pub mod declaration; pub use declaration::*;
pub mod aceident; pub use aceident::*;
pub mod from; pub use from::*;
pub mod aceselectorimpl_; pub use aceselectorimpl_::*;
pub mod aceselectorimpl; pub use aceselectorimpl::*;
pub mod acepseudoelement; pub use acepseudoelement::*;
pub mod acenontspseudoclass; pub use acenontspseudoclass::*;
pub mod aceelement; pub use aceelement::*;
pub mod aceelement_impl_1; pub use aceelement_impl_1::*;
pub mod aceelement_impl_2; pub use aceelement_impl_2::*;
pub mod aceelement_impl_3; pub use aceelement_impl_3::*;
pub mod get_user_agent_stylesheet; pub use get_user_agent_stylesheet::*;
pub mod parse_media_rule; pub use parse_media_rule::*;
pub mod parse_supports_rule; pub use parse_supports_rule::*;
pub mod parse_container_rule; pub use parse_container_rule::*;
pub mod parse_font_face_rule; pub use parse_font_face_rule::*;
pub mod parse_keyframes_rule; pub use parse_keyframes_rule::*;
pub mod parse; pub use parse::*;
pub mod acestyleruleparser_; pub use acestyleruleparser_::*;
pub mod expand_box_shorthand; pub use expand_box_shorthand::*;
pub mod expand_border; pub use expand_border::*;
pub mod expand_outline; pub use expand_outline::*;
pub mod expand_background; pub use expand_background::*;
pub mod expand_font; pub use expand_font::*;
pub mod acestyleruleparser; pub use acestyleruleparser::*;
pub mod parse_simple; pub use parse_simple::*;
pub mod aceselectorparser_; pub use aceselectorparser_::*;
pub mod aceselectorparser; pub use aceselectorparser::*;
pub mod cascadeorigin; pub use cascadeorigin::*;
pub mod cascadepriority; pub use cascadepriority::*;
pub mod matchedrule; pub use matchedrule::*;
pub mod inherit_from_parent; pub use inherit_from_parent::*;
pub mod apply_matched_rules; pub use apply_matched_rules::*;
pub mod apply_inline_styles; pub use apply_inline_styles::*;
pub mod stylesheet_impl_1; pub use stylesheet_impl_1::*;
pub mod stylesheet_impl_2; pub use stylesheet_impl_2::*;
pub mod stylesheet_impl_3; pub use stylesheet_impl_3::*;
pub mod parse_length; pub use parse_length::*;
pub mod parse_grid_placement; pub use parse_grid_placement::*;
pub mod split_comma_top_level; pub use split_comma_top_level::*;
pub mod _parse_length_list; pub use _parse_length_list::*;
pub mod split_spaces_top_level; pub use split_spaces_top_level::*;
pub mod parse_grid_track_list; pub use parse_grid_track_list::*;
pub mod parse_grid_template_areas; pub use parse_grid_template_areas::*;
pub mod parse_content; pub use parse_content::*;
pub mod parse_color; pub use parse_color::*;
pub mod parse_display; pub use parse_display::*;
pub mod parse_position; pub use parse_position::*;
pub mod parse_overflow; pub use parse_overflow::*;
pub mod parse_float; pub use parse_float::*;
pub mod parse_clear; pub use parse_clear::*;
pub mod parse_text_transform; pub use parse_text_transform::*;
pub mod parse_text_overflow; pub use parse_text_overflow::*;
pub mod parse_flex_direction; pub use parse_flex_direction::*;
pub mod parse_justify_content; pub use parse_justify_content::*;
pub mod parse_align_items; pub use parse_align_items::*;
pub mod parse_align_content; pub use parse_align_content::*;
pub mod parse_flex_wrap; pub use parse_flex_wrap::*;
pub mod parse_border_radius; pub use parse_border_radius::*;
pub mod parse_text_align; pub use parse_text_align::*;
pub mod parse_font_weight; pub use parse_font_weight::*;
pub mod parse_box_sizing; pub use parse_box_sizing::*;
pub mod parse_visibility; pub use parse_visibility::*;
pub mod parse_cursor; pub use parse_cursor::*;
pub mod parse_object_fit; pub use parse_object_fit::*;
pub mod parse_object_position; pub use parse_object_position::*;
pub mod parse_pointer_events; pub use parse_pointer_events::*;
pub mod parse_filters; pub use parse_filters::*;
pub mod parse_blend_mode; pub use parse_blend_mode::*;
pub mod parse_transitions; pub use parse_transitions::*;
pub mod parse_animations; pub use parse_animations::*;
pub mod parse_transform; pub use parse_transform::*;
pub mod parse_box_shadow; pub use parse_box_shadow::*;
pub mod parse_text_shadow; pub use parse_text_shadow::*;
pub mod parse_background_image; pub use parse_background_image::*;
pub mod parse_linear_gradient; pub use parse_linear_gradient::*;
pub mod parse_radial_gradient; pub use parse_radial_gradient::*;
pub mod parse_color_stops; pub use parse_color_stops::*;
pub mod resolve_css_variables; pub use resolve_css_variables::*;
pub mod resolve_css_variables_recursive; pub use resolve_css_variables_recursive::*;
pub mod resolve_length; pub use resolve_length::*;
pub mod parse_inline_declarations; pub use parse_inline_declarations::*;
pub mod apply_margin_shorthand; pub use apply_margin_shorthand::*;
pub mod apply_padding_shorthand; pub use apply_padding_shorthand::*;
pub mod default_outline; pub use default_outline::*;
pub mod apply_outline_property; pub use apply_outline_property::*;
pub mod apply_grid_property; pub use apply_grid_property::*;
pub mod resolve_rel_static; pub use resolve_rel_static::*;
pub mod apply_aspect_ratio; pub use apply_aspect_ratio::*;
pub mod apply_flexbox_property; pub use apply_flexbox_property::*;
pub mod apply_border_detail; pub use apply_border_detail::*;
pub mod apply_typography; pub use apply_typography::*;
pub mod apply_basic_layout; pub use apply_basic_layout::*;
pub mod apply_box_sides; pub use apply_box_sides::*;
pub mod apply_text_and_misc; pub use apply_text_and_misc::*;
pub mod apply_single_declaration; pub use apply_single_declaration::*;
pub mod matches_media_query; pub use matches_media_query::*;
pub mod matches_media_query_part; pub use matches_media_query_part::*;
pub mod matches_feature; pub use matches_feature::*;
pub mod matches_supports; pub use matches_supports::*;
pub mod matches_container; pub use matches_container::*;
