//! Accessibility Tree (ARIA 1.2) Implementation - W3C WAI-ARIA Spec
//! 
//! Este módulo implementa:
//! - Mapeamento implícito de roles HTML → ARIA
//! - Accessible Name Computation (AccName 1.2)
//! - States & Properties ARIA
//! - Relations (aria-controls, aria-owns, etc.)
//! - Tree traversal para screen readers

use super::*;
use std::collections::HashMap;
use crate::ace::engine::dom::{AceDOM, AceNodeType};

/// Role ARIA de um elemento

#[derive(Clone, Debug, PartialEq)]
pub enum AriaRole {
    // Widget Roles
    Button,
    Checkbox,
    Combobox,
    Gridcell,
    Link,
    Listbox,
    Menuitem,
    Menuitemcheckbox,
    Menuitemradio,
    Option,
    Progressbar,
    Radio,
    Scrollbar,
    Searchbox,
    Slider,
    Spinbutton,
    Switch,
    Tab,
    Tabpanel,
    Textbox,
    Treeitem,
    
    // Composite Roles
    Grid,
    ListBoxComposite,
    Menu,
    Menubar,
    Radiogroup,
    Tablist,
    Tree,
    Treegrid,
    
    // Document Structure Roles
    Application,
    Article,
    Cell,
    Columnheader,
    Definition,
    Directory,
    Document,
    Feed,
    Figure,
    Group,
    Heading,
    Img,
    List,
    ListItem,
    Math,
    None,
    Note,
    Presentation,
    Row,
    Rowgroup,
    Rowheader,
    Separator,
    Table,
    Term,
    Toolbar,
    Tooltip,
    
    // Landmark Roles
    Banner,
    Complementary,
    Contentinfo,
    Form,
    Main,
    Navigation,
    Region,
    Search,
    
    // Live Region Roles
    Alert,
    Log,
    Marquee,
    Status,
    Timer,
    
    // Window Roles
    Alertdialog,
    Dialog,
    
    // Fallback
    Generic,
}

impl AriaRole {
    /// Retorna a string ARIA correspondente
    pub fn as_str(&self) -> &'static str {
        match self {
            AriaRole::Button => "button",
            AriaRole::Checkbox => "checkbox",
            AriaRole::Combobox => "combobox",
            AriaRole::Gridcell => "gridcell",
            AriaRole::Link => "link",
            AriaRole::Listbox => "listbox",
            AriaRole::Menuitem => "menuitem",
            AriaRole::Menuitemcheckbox => "menuitemcheckbox",
            AriaRole::Menuitemradio => "menuitemradio",
            AriaRole::Option => "option",
            AriaRole::Progressbar => "progressbar",
            AriaRole::Radio => "radio",
            AriaRole::Scrollbar => "scrollbar",
            AriaRole::Searchbox => "searchbox",
            AriaRole::Slider => "slider",
            AriaRole::Spinbutton => "spinbutton",
            AriaRole::Switch => "switch",
            AriaRole::Tab => "tab",
            AriaRole::Tabpanel => "tabpanel",
            AriaRole::Textbox => "textbox",
            AriaRole::Treeitem => "treeitem",
            AriaRole::Grid => "grid",
            AriaRole::ListBoxComposite => "listbox",
            AriaRole::Menu => "menu",
            AriaRole::Menubar => "menubar",
            AriaRole::Radiogroup => "radiogroup",
            AriaRole::Tablist => "tablist",
            AriaRole::Tree => "tree",
            AriaRole::Treegrid => "treegrid",
            AriaRole::Application => "application",
            AriaRole::Article => "article",
            AriaRole::Cell => "cell",
            AriaRole::Columnheader => "columnheader",
            AriaRole::Definition => "definition",
            AriaRole::Directory => "directory",
            AriaRole::Document => "document",
            AriaRole::Feed => "feed",
            AriaRole::Figure => "figure",
            AriaRole::Group => "group",
            AriaRole::Heading => "heading",
            AriaRole::Img => "img",
            AriaRole::List => "list",
            AriaRole::ListItem => "listitem",
            AriaRole::Math => "math",
            AriaRole::None => "none",
            AriaRole::Note => "note",
            AriaRole::Presentation => "presentation",
            AriaRole::Row => "row",
            AriaRole::Rowgroup => "rowgroup",
            AriaRole::Rowheader => "rowheader",
            AriaRole::Separator => "separator",
            AriaRole::Table => "table",
            AriaRole::Term => "term",
            AriaRole::Toolbar => "toolbar",
            AriaRole::Tooltip => "tooltip",
            AriaRole::Banner => "banner",
            AriaRole::Complementary => "complementary",
            AriaRole::Contentinfo => "contentinfo",
            AriaRole::Form => "form",
            AriaRole::Main => "main",
            AriaRole::Navigation => "navigation",
            AriaRole::Region => "region",
            AriaRole::Search => "search",
            AriaRole::Alert => "alert",
            AriaRole::Log => "log",
            AriaRole::Marquee => "marquee",
            AriaRole::Status => "status",
            AriaRole::Timer => "timer",
            AriaRole::Alertdialog => "alertdialog",
            AriaRole::Dialog => "dialog",
            AriaRole::Generic => "generic",
        }
    }
    
    /// Parse de string para AriaRole
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "button" => Some(AriaRole::Button),
            "checkbox" => Some(AriaRole::Checkbox),
            "combobox" => Some(AriaRole::Combobox),
            "link" => Some(AriaRole::Link),
            "listbox" => Some(AriaRole::Listbox),
            "menuitem" => Some(AriaRole::Menuitem),
            "option" => Some(AriaRole::Option),
            "progressbar" => Some(AriaRole::Progressbar),
            "radio" => Some(AriaRole::Radio),
            "searchbox" => Some(AriaRole::Searchbox),
            "slider" => Some(AriaRole::Slider),
            "spinbutton" => Some(AriaRole::Spinbutton),
            "switch" => Some(AriaRole::Switch),
            "tab" => Some(AriaRole::Tab),
            "tabpanel" => Some(AriaRole::Tabpanel),
            "textbox" => Some(AriaRole::Textbox),
            "treeitem" => Some(AriaRole::Treeitem),
            "grid" => Some(AriaRole::Grid),
            "menu" => Some(AriaRole::Menu),
            "menubar" => Some(AriaRole::Menubar),
            "radiogroup" => Some(AriaRole::Radiogroup),
            "tablist" => Some(AriaRole::Tablist),
            "tree" => Some(AriaRole::Tree),
            "article" => Some(AriaRole::Article),
            "cell" => Some(AriaRole::Cell),
            "columnheader" => Some(AriaRole::Columnheader),
            "definition" => Some(AriaRole::Definition),
            "document" => Some(AriaRole::Document),
            "figure" => Some(AriaRole::Figure),
            "group" => Some(AriaRole::Group),
            "heading" => Some(AriaRole::Heading),
            "img" => Some(AriaRole::Img),
            "list" => Some(AriaRole::List),
            "listitem" => Some(AriaRole::ListItem),
            "math" => Some(AriaRole::Math),
            "none" => Some(AriaRole::None),
            "note" => Some(AriaRole::Note),
            "presentation" => Some(AriaRole::Presentation),
            "row" => Some(AriaRole::Row),
            "rowgroup" => Some(AriaRole::Rowgroup),
            "rowheader" => Some(AriaRole::Rowheader),
            "separator" => Some(AriaRole::Separator),
            "table" => Some(AriaRole::Table),
            "term" => Some(AriaRole::Term),
            "toolbar" => Some(AriaRole::Toolbar),
            "tooltip" => Some(AriaRole::Tooltip),
            "banner" => Some(AriaRole::Banner),
            "complementary" => Some(AriaRole::Complementary),
            "contentinfo" => Some(AriaRole::Contentinfo),
            "form" => Some(AriaRole::Form),
            "main" => Some(AriaRole::Main),
            "navigation" => Some(AriaRole::Navigation),
            "region" => Some(AriaRole::Region),
            "search" => Some(AriaRole::Search),
            "alert" => Some(AriaRole::Alert),
            "log" => Some(AriaRole::Log),
            "status" => Some(AriaRole::Status),
            "timer" => Some(AriaRole::Timer),
            "alertdialog" => Some(AriaRole::Alertdialog),
            "dialog" => Some(AriaRole::Dialog),
            _ => None,
        }
    }
}
